stages:
  - build
  - deploy

# 🔹 BUILD STAGE
build_react:
  image: node:18
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

# 🔹 DEPLOY STAGE
deploy_react:
  image: alpine
  stage: deploy
  dependencies:
    - build_react

  # ✅ Run only on main branch
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh

    # ✅ Add SSH key
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # ✅ Avoid host verification issue
    - ssh-keyscan -H 16.112.63.158 >> ~/.ssh/known_hosts

  script:
    - ssh ubuntu@16.112.63.158 "echo build success"

  environment:
    name: production